/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package covidmanagementsystem.managementsystem;

/**
 *
 * @author 123
 */
public class Manager_menu extends javax.swing.JFrame {
    String username;
    /**
     * Creates new form Manager_menu
     */
    public Manager_menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        statisticBtn = new javax.swing.JButton();
        necessitiesManagementBtn = new javax.swing.JButton();
        userManagementBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Covid Management Systems");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1520, 90));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        statisticBtn.setBackground(new java.awt.Color(0, 0, 255));
        statisticBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        statisticBtn.setForeground(new java.awt.Color(255, 255, 255));
        statisticBtn.setText("Statistics");
        statisticBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticBtnActionPerformed(evt);
            }
        });
        jPanel3.add(statisticBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 210, 330, 130));

        necessitiesManagementBtn.setBackground(new java.awt.Color(0, 0, 255));
        necessitiesManagementBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        necessitiesManagementBtn.setForeground(new java.awt.Color(255, 255, 255));
        necessitiesManagementBtn.setText("Necessities Management");
        necessitiesManagementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                necessitiesManagementBtnActionPerformed(evt);
            }
        });
        jPanel3.add(necessitiesManagementBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 410, 130));

        userManagementBtn.setBackground(new java.awt.Color(0, 0, 255));
        userManagementBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        userManagementBtn.setForeground(new java.awt.Color(255, 255, 255));
        userManagementBtn.setText("User Management");
        userManagementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userManagementBtnActionPerformed(evt);
            }
        });
        jPanel3.add(userManagementBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 330, 130));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 1520, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void necessitiesManagementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_necessitiesManagementBtnActionPerformed
        Manager_necessities_management necessitiesManagement=new Manager_necessities_management();
        necessitiesManagement.setVisible(true); 
    }//GEN-LAST:event_necessitiesManagementBtnActionPerformed

    private void userManagementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userManagementBtnActionPerformed
        Mananger_user_management userManagement=new Mananger_user_management();
        userManagement.setVisible(true); 
    }//GEN-LAST:event_userManagementBtnActionPerformed

    private void statisticBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticBtnActionPerformed
        Statistics stat=new Statistics();
        stat.setVisible(true);
    }//GEN-LAST:event_statisticBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton necessitiesManagementBtn;
    private javax.swing.JButton statisticBtn;
    private javax.swing.JButton userManagementBtn;
    // End of variables declaration//GEN-END:variables
}
